{{ if .Values.secret.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole-exporter.fullname" . }}
  labels:
{{ include "pihole-exporter.labels" . | indent 4 }}
type: Opaque
data:
  {{- with .Values.secret.secretEnvVars }}
  {{- if .PIHOLE_PASSWORD }}
  PIHOLE_PASSWORD:  {{ .PIHOLE_PASSWORD | b64enc | quote }}
  {{- end }}
  {{- if .PIHOLE_API_TOKEN }}
  PIHOLE_API_TOKEN:  {{ .PIHOLE_API_TOKEN | b64enc | quote }}
  {{- end }}
  {{- end }}
{{ end }}